---
    name: disha-tira-test-deployment-pipeline
    on:
      push:
        branches:
          - test
    jobs:
      web-deploy:
        name: 🎉 Deploy-test-branch
        runs-on: ubuntu-latest
        steps:
          - name: 🚚 Get latest code
            uses: actions/checkout@v3
          - name: Use Node.js 16
            uses: actions/setup-node@v4
            with:
              node-version: '16'
          - name: 🔨 Install dependencies
            run: |
              pwd
              npm i --force
          - name: Building the react js project
            run: |
              npm run build
            env:
              CI: false
          - name: Checking the path and the data
            run: |
              ls -la
              cd build/
              ls -la
              pwd
          - name: 📂 Sync files
            uses: SamKirkland/FTP-Deploy-Action@v4.3.4
            with:
              local-dir: /home/runner/work/disha_tira_webApp/disha_tira_webApp/build
              server: 217.21.91.239
              username: u134273879.disha_rr_tira_test_ftp_user
              password: ${{ secrets.DISHA_TIRA_TEST_FTP_PWD }}