name: dishatest-website-deployment-pipelinenew
on:
  push:
    branches:
      - dishaTest

jobs:
    web-deploy:
      name: 🎉 Deploy-main-branch
      runs-on: ubuntu-latest
      steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v3
    
        - name: Use Node.js 16
          uses: actions/setup-node@v4
          with:
            node-version: '16'
            
          
        - name: 🔨 Install dependencies
          run: |
            pwd
            npm i --force
            
        - name: Building the react js project
          run: |
            npm run build
          env:
            CI: false
        
        - name: Checking the path and the data
          run: |
            ls -la
            cd build/
            ls -la
            pwd
      
        - name: 📂 Sync files
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
            local-dir: '/home/runner/work/disha_fashion/disha_fashion/build/'
            server: '217.21.91.239'
            username: u134273879.disha_fashion_ftp
            password: ${{ secrets.DISHA_FTP_PWD }}